### ISSUE TITLE
How to support asciidoctor-diagram and source highlighting?

### ISSUE THREAD

**Issue by gudaoxuri** [asciibook/asciibook#2]
This is a great tool. 

But currently it does not support for diagram rendering （E.g. plantUML） and code highlighting.

I hope to be able to provide support for these capabilities, thank you.

**Comment by gudaoxuri** [comment]
> Source highlight is supported. Add this config in the head of document:
> 
> ```
> :source-highlighter: rouge
> ```
> 
> This is a document missing. Because asciibook only supports rouge, maybe I should set it as the default value?
> 
> I also found that there is an incorrect padding in the code block style. I will release an update to fix it later.
> 
> Asciidoctor-diagram has a lot of dependencies, the docker image may become very large. Can you tell me which format you want to use?
> 
> https://docs.asciidoctor.org/diagram-extension/latest/#creating-a-diagram
> 
> I am not sure whether to implement it. If it is not, I will write a document on how to build a docker image to extend the function.

Thanks for the reply.

Source highlighting works now.

I commonly use plantuml ( https://github.com/hsanson/asciidoctor-plantuml ). It's a good idea to provide extended solutions to support different needs.

**Comment by chloerei** [comment]
I took a look at asciidoctor-plantuml, it require external PlantUML server, unlike asciibook's expectations as a single executable docker image.

Current recommendation is to edit the diagram independently and then embed it in document as image.

**Comment by gudaoxuri** [comment]
> 

Should be able to direct public services （ http://plantuml.com/plantuml ） , similar to the asciidoc plantuml plugin in vs code.

https://blog.anoff.io/2019-05-08-asciidoc-plantuml-vscode/

**Comment by chloerei** [comment]
I consider implementing a plugin mechanism that allows require ruby gems or ruby scripts. The API looks like:

```console
asciibook build -r asciidoctor-plantuml -r path/to/script book.adoc
```

or in config.yml:

```yaml
plugins:
  - asciidoctor-plantuml
  - path/to/script
```

**Comment by chloerei** [comment]
I added plugin support and some docs, and release v0.0.5 docker image.

First pull the new image:

```console
docker pull asciibook/asciibook:0.0.5
```

Then follow this docs:

- Using plugin: https://asciibook.org/docs/_plugin.html
- Build custom image: https://asciibook.org/docs/_build_docker_image.html

I tested and found that asciidoctor-diagram is fully compatible with the default style of asciibook. Asciidoctor-plantuml hard-codes the html output, so you need to add your own style settings.

If you can accept that the image becomes larger, I would recommend using asciidoctor-diagram.

I'm not sure if the document is clear, you can comment here if you have any questions.

**Comment by gudaoxuri** [comment]
It works for me. The document description is very clear. Thank you so much.

**Comment by chloerei** [comment]
Good!
